-- 1. Join the film to the film_actor table.
SELECT F.*, FA.ACTOR_ID, FA.LAST_UPDATE FILM_ACTOR_LAST_UPDATE
FROM FILM F
JOIN FILM_ACTOR FA
ON F.FILM_ID = FA.FILM_ID

-- 2. Join the actor table to the film_actor table. 
SELECT A.*,FA.FILM_ID, FA.LAST_UPDATE FILM_ACTOR_LAST_UPDATE
FROM ACTOR A
JOIN FILM_ACTOR FA
ON A.ACTOR_ID = FA.ACTOR_ID

--3. Try to join the actor, film_actor, and film table together (3 joins!)
SELECT F.*, A.ACTOR_ID, A.FIRST_NAME, A.LAST_NAME, A.LAST_UPDATE ACTOR_LAST_UPDATE, FA.LAST_UPDATE FILM_ACTOR_LAST_UPDATE
FROM FILM F
JOIN ACTOR A
JOIN FILM_ACTOR FA
ON FA.ACTOR_ID = A.ACTOR_ID
ON F.FILM_ID = FA.FILM_ID